[package]
name = "tower-buffer"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]
publish = false
edition = "2018"

[dependencies]
futures = "0.1.25"
tower-service = "0.2.0"
tower-layer = { version = "0.1", path = "../tower-layer" }
tokio-executor = "0.1.7"
tokio-sync = "0.1.0"

[dev-dependencies]
tower = { version = "0.1", path = "../tower" }
tower-test = { version = "0.1", path = "../tower-test" }
