[package]
name = "tower-buffer"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]
publish = false

[dependencies]
futures = "0.1"
tower-service = { version = "0.2", path = "../tower-service" }
tower-layer = { version = "0.1", path = "../tower-layer" }
tokio-executor = "0.1"
tokio-sync = "0.1"

[dev-dependencies]
tower-mock = { version = "0.1", path = "../tower-mock" }
