[package]
name = "tower-balance"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]
publish = false

[dependencies]
futures = "0.1"
log = "0.3"
rand = "0.4"
tower = { version = "0.1", path = "../" }
tower-discover = { version = "0.1", path = "../tower-discover" }
indexmap = "0.4.1"

[dev-dependencies]
log = "0.3"
env_logger = "0.4"
hdrsample = "6.0"
tokio-core = "^0.1.12"
tokio-timer = "0.1"
quickcheck = "0.6"
