[package]
name = "tower-balance"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]
publish = false

[dependencies]
futures = "0.1"
log = "0.4.1"
rand = "0.6"
tokio-timer = "0.2.4"
tower-service = "0.2.0"
tower-discover = { version = "0.1", path = "../tower-discover" }
tower-util = { version = "0.1", path = "../tower-util" }
indexmap = "1"

[dev-dependencies]
log = "0.4.1"
env_logger = { version = "0.5.3", default-features = false }
hdrsample = "6.0"
quickcheck = { version = "0.6", default-features = false }
tokio = "0.1.7"
tokio-executor = "0.1.2"
tower-buffer = { version = "0.1", path = "../tower-buffer" }
tower-in-flight-limit = { version = "0.1", path = "../tower-in-flight-limit" }
