[package]

name = "tower-util"
# When releasing to crates.io:
# - Update html_root_url.
# - Update CHANGELOG.md.
# - Update documentation URL
# - Create "v0.x.y" git tag.
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/tower-rs/tower"
homepage = "https://github.com/tower-rs/tower"
documentation = "https://docs.rs/tokio-util/0.1.0"
description = """
Utilities for working with tower-service.
"""
categories = ["asynchronous", "network-programming"]

[features]
io = ["tokio-io"]

[dependencies]
futures = "0.1.23"
tokio-io = { version = "0.1.12", optional = true }
tower-service = "0.2.0"
tower-layer = { version = "0.1.0", path = "../tower-layer" }

[dev-dependencies]
tokio-mock-task = "0.1"
tower = { version = "0.1.0", path = "../tower" }
tower-mock = { version = "0.1.0", path = "../tower-mock" }
