[package]
name = "tower-util"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]
publish = false

[dependencies]
futures = "0.1"
tower-service = "0.2.0"
tokio-io = "0.1"

[dev-dependencies]
tokio-mock-task = "0.1"
