[package]

name = "tower-util"
# When releasing to crates.io:
# - Remove path dependencies
# - Update html_root_url.
# - Update doc url
#   - Cargo.toml
#   - README.md
# - Update CHANGELOG.md.
# - Create "v0.3.x" git tag.
version = "0.3.0-alpha.1"
authors = ["Tower Maintainers <team@tower-rs.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/tower-rs/tower"
homepage = "https://github.com/tower-rs/tower"
documentation = "https://docs.rs/tower-util/0.3.0-alpha.1"
description = """
Utilities for working with `Service`.
"""
categories = ["asynchronous", "network-programming"]
edition = "2018"

[dependencies]
tower-service = "=0.3.0-alpha.1"
tower-layer = { version = "=0.3.0-alpha.1", path = "../tower-layer" }
pin-project = "0.4"
futures-util-preview = "=0.3.0-alpha.18"
futures-core-preview = "=0.3.0-alpha.18"

[dev-dependencies]
futures-util-preview = "=0.3.0-alpha.18"
tokio-test = { git = "https://github.com/tokio-rs/tokio"}
tokio = { git = "https://github.com/tokio-rs/tokio"}
tower = { version = "=0.3.0-alpha.1a", path = "../tower" }
tower-test = { version = "=0.3.0-alpha.1", path = "../tower-test" }
