[package]
edition = "2018"
name = "tower-retry"
version = "0.1.0"
authors = ["Sean McArthur <sean@seanmonstar.com>"]
publish = false

[dependencies]
futures = "0.1"
tower-service = { version = "0.2", path = "../tower-service" }
tokio-timer = "0.2.4"

[dev-dependencies]
tower-mock = { version = "0.1", path = "../tower-mock" }
tokio-executor = "0.1.2"
