[package]
name = "tower-retry"
version = "0.1.0"
authors = ["Sean McArthur <sean@seanmonstar.com>"]
publish = false
edition = "2018"

[dependencies]
futures = "0.1"
tower-service = "0.2.0"
tower-layer = { version = "0.1", path = "../tower-layer" }
tokio-timer = "0.2.4"

[dev-dependencies]
tower-test = { version = "0.1", path = "../tower-test" }
tokio-executor = "0.1.2"
