[package]
name = "tower-layer"
# When releasing to crates.io:
# - Update html_root_url.
# - Update documentation URL
# - Create "v0.x.y" git tag.
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/tower-rs/tower"
homepage = "https://github.com/tower-rs/tower"
documentation = "https://docs.rs/tokio-layer/0.1.0"
description = """
Decorates a `Service` to allow easy composition between `Service`s.
"""
categories = ["asynchronous", "network-programming"]

[dependencies]
futures = "0.1"
tower-service = "0.2.0"

[features]
default = ["util"]
util = []
