[package]
name = "tower-watch"
version = "0.1.0"
authors = ["Oliver Gould <ver@buoyant.io>"]

[dependencies]
futures = "0.1.21"
futures-watch = { git = "https://github.com/carllerche/better-future" }
tower-service = { version = "0.1", path = "../tower-service" }

[dev-dependencies]
tokio = "0.1.7"
