[package]
name = "tower-filter"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]
publish = false

[dependencies]
futures = "0.1"
tower = { version = "0.1", path = "../" }

[dev-dependencies]
tower-mock = { version = "0.1", path = "../tower-mock" }
